baseball/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import UserViewSet

router = routers.DefaultRouter()
router.register('users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

baseball/baseball/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("team/", include('team.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('store/', include('store.urls')),
]

baseball/blog/urls.py
from django.urls import path, reverse, reverse_lazy
from . import views
from .models import *

app_name = 'blog'

urlpatterns = [
    path('', views.list, name='list'),
    path('new/',views.create, name='create'),
    path('<int:no>/',views.detail, name='detail'),
    path('profile/', views.profile),
    path('tag/<id>/',views.tag_list),
    path('update/<id>/', views.post_update, name='update'),
    path('delete/<id>/', views.post_delete, name='delete'),
]

baseball/blog/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from accounts.models import MyUser

# Create your models here.

class Post(models.Model):
    
    def __str__(self):
        return self.title  
    
    title = models.CharField(max_length=250)
    body = models.TextField()
    tag = models.ManyToManyField('Tag', null=True, blank=True)
    ip = models.GenericIPAddressField(null=True)
    
    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.id])
    


class Comment(models.Model):
    
    post = models.ForeignKey(Post, on_delete= models.CASCADE, related_name='comments')
    author = models.CharField(max_length=20)
    message = models.TextField()
    created = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=True)
    

class Tag(models.Model):
    
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name
    

class Profile(models.Model):
    
    user = models.OneToOneField(MyUser, on_delete=models.CASCADE,related_name='profile')
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    
    
    

baseball/blog/forms.py
from django import forms
from blog.models import Post

class PostFrom(forms.Form):
    
    title = forms.CharField(label='제목')
    body = forms.CharField(label='내용', widget=forms.Textarea)
    

class PostModelForm(forms.ModelForm):
    
    class Meta:
        
        model = Post
        fields = ['title','body']
        
        

baseball/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpRequest
from .models import *
from .forms import *
from accounts.models import MyUser
from django.contrib.auth.decorators import login_required

# Create your views here.

def list(request):
    post_list = Post.objects.all()
    
    return render(request, 'blog/list.html', {'post_all': post_list})

def create(request):
    
    if request.method == 'POST':
        form = PostModelForm(request.POST)
        if form.is_valid():
            print('cleaned_data', form.cleaned_data)
            
            post = form.save(commit=False)
            post.ip = request.META['REMOTE_ADDR']
            post.save()
            return redirect(post)
        
    else:
        form = PostModelForm()
        
    return render(request, 'blog/post_form.html',{'form':form})

def post_update(request, id):
    
    post = get_object_or_404(Post, id=id)
    
    if request.method == 'POST':
        form = PostModelForm(request.POST, instance = post)
        
        if form.is_valid(): 
            form.save()
            return redirect('blog:list')
        
    else:
        form = PostModelForm(instance=post)
    
    return render(request, 'blog/post_update.html', {'form':form})
        

def post_delete(request, id):
    
    post = get_object_or_404(Post, id=id)
    
    if request.method =='POST':
        post.delete()
        return redirect('blog:list')
    
    else:
        return render(request, 'blog/post_delete.html',{'post':post})


def detail(request,no):
    post = get_object_or_404(Post, id=no)
    comment_list = post.comments.all()
    tag_list = post.tag.all()
    
    return render(request, 'blog/post_detail.html',{'post':post, 'comment_list':comment_list, 'tag_list':tag_list})    


def profile(request):
    user = request.user
    
    return render(request, 'blog/profile.html', {'user':user})

    
def tag_list(request, id):
    
    tag = Tag.objects.all(id=id)
    
    post_list = tag.post_set.all()
    
    return render(request,'blog/list.html',{'post_all': post_list})


    
    
    

baseball/blog/templates/blog/detail.html
{% block title %}상세 보기{% endblock title %}


{% block content %}

    <h1>{{post.title}}</h1>

    제목 : {{post.title}} <br>
    내용 : {{post.body}} <br>

    <hr>
    <p>댓글</p>
    {% for comment in comment_all %}
        <p>{{comment.message}} / {{comment.author}} / {{comment.updated}} </p>
    {% empty %} 
        <p> 댓글이 존재하지 않습니다. </p> 
    {% endfor %}

    <hr>
    <p>태그</p>
    {% for tag in tag_list %}
        {{tag.name}} 
    {% endfor %}
    <hr>
    <a href="{% url 'blog:list' %}">[목록 보기]</a>

{% endblock content %}

baseball/blog/templates/blog/list.html
{% extends "layout.html" %}

{% block title %}Post 목록 보기{% endblock title %}

{% block content %}

<h1>Post 목록 보기</h1>

    {% for post in post_all %}
        <a href ='/blog/{{post.id}}'>{{post.title}}</a><br>
    {% endfor %}

    <a href="{% url 'blog:create' %}">[새 글 쓰기]</a>

{% endblock content %}

baseball/blog/templates/blog/post_delete.html
{% extends "layout.html" %}
{% block title %}Post 삭제{% endblock %}
{% block content %}
    <h1> POST 삭제</h1>
    {{post}}  글을 정말로 삭제하시겠습니까?

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="네, 삭제합니다">
    </form>

    <a href="{% url 'blog:list'%}">아니오, 취소합니다</a>
    
{% endblock %}

baseball/blog/templates/blog/post_detail.html
{% extends "layout.html" %}
{% block title %}상세 보기{% endblock title %}


{% block content %}

    <h1>{{post.title}}</h1>

    제목 : {{post.title}} <br>
    내용 : {{post.body}} <br>

    <hr>
    <p>댓글</p>
    {% for comment in comment_all %}
        <p>{{comment.message}} / {{comment.author}} / {{comment.updated}} </p>
    {% empty %} 
        <p> 댓글이 존재하지 않습니다. </p> 
    {% endfor %}

    <hr>
    <p>태그</p>
    {% for tag in tag_list %}
        # <a href = "/blog/tag/{{tag.id}}/">{{tag.name}} </a>
    {% endfor %}
    <hr>
    <a href="{% url 'blog:list' %}">[목록 보기]</a>
    <a href="{% url 'blog:update' post.id %}">[글 수정]</a>
    <a href="{% url 'blog:delete' post.id %}">[글 삭제]</a>


{% endblock content %}

baseball/blog/templates/blog/post_form.html
{% extends "layout.html" %}
{% block title %} Post 등록 {% endblock %}
{% block content %}
    <h1> POST 등록</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="등록">
    </form>
{% endblock %}

baseball/blog/templates/blog/post_update.html
{% extends "layout.html" %}
{% block title %}Post 수정{% endblock %}

{% block content %}
    <h1> POST 수정</h1>

    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="수정">
    </form>
{% endblock %}

baseball/blog/templates/blog/profile.html
{% extends "layout.html" %}
{% block title %}  
    profile
{% endblock %}
{% block content %}
    <h1> {{user}}'s Profile </h1>
    <ul>
        <li>이름:{{user.name}}</li>
        <li>전화번호:{{user.profile.phone_number}}</li>
        <li>주소:{{user.profile.address}}</li>
    </ul>
{% endblock %}