baseball/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import UserViewSet

router = routers.DefaultRouter()
router.register('users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

baseball/baseball/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("team/", include('team.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('store/', include('store.urls')),
]

baseball/team/urls.py
from django.urls import path, reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView
from . import views
from .models import *

app_name = 'team'

urlpatterns = [
    
    path('', ListView.as_view(model=Team), name = 'list'),
    path('detail/<pk>/', DetailView.as_view(model=Team), name = 'detail'),
    path('create/', CreateView.as_view(model=Team, fields = '__all__'), name='create'),
    path('update/<pk>/', UpdateView.as_view(model=Team, fields = '__all__'), name='update'),
    path('delete/<pk>/', DeleteView.as_view(model=Team, success_url = reverse_lazy('team:list')), name='delete'),
]

baseball/team/models.py
from django.db import models
from django.urls import path, reverse

# Create your models here.

class Team(models.Model):
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('team:list')
    
    name = models.CharField(max_length=30)
    level = models.IntegerField()
    COUNTRY_CHOICES = [
        ('usa', 'USA'),
        ('korea', 'Korea'),
        ('japan', 'Japan'),
    ]
    
    country = models.CharField(
        max_length=5, choices= COUNTRY_CHOICES,
        default='korea',
    )

    

class Member(models.Model):
    
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='members')
    name = models.CharField(max_length=20)
    age = models.IntegerField()
    position = models.CharField(max_length=20)
    staff = models.BooleanField()

    def __str__(self):
        return self.name




baseball/team/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.http import HttpResponse
from . models import *
from . forms import *
# Create your views here.


def test1(request):
    
    return HttpResponse("hello")

baseball/team/templates/team/team_confirm_delete.html
{% extends "layout.html" %}
{% block title %}Post 삭제{% endblock %}
{% block content %}
    <h1> Team 삭제</h1>

    "{{team}}"을 정말로 삭제하시겠습니까?
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="네, 삭제합니다">
    </form>
    <a href="{% url 'team:list'%}">아니오, 취소합니다</a>
    
{% endblock %}

baseball/team/templates/team/team_detail.html
{% extends "layout.html" %}
{% block title %} Team 상세보기 {% endblock %}
{% block content %}
    <h1>{{team.name}}</h1>
    팀 이름 : {{team.name}} <br>
    군 : {{team.level}} <br>
    나라 : {{team.country}}<br>
    <a href="{% url 'team:update' team.id %}">[수정하기]</a>
    <a href="{% url 'team:delete' team.id %}">[삭제하기]</a> 
{% endblock %}

baseball/team/templates/team/team_form.html
{% extends "layout.html" %}
{% block title %}
  Team 등록
{% endblock %}
{% block content %}
  <h1>Team 등록</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" value="등록" />
  </form>
{% endblock %}


baseball/team/templates/team/team_list.html
{% extends "layout.html" %}
{% block title %} Team 목록 {% endblock %}
{% block content %}
    <h1>Team 목록 보기</h1>
    {% for team in team_list %}
        <a href="{% url 'team:detail' team.id %}"> {{team.name}} {{team.level}}</a><br>
    {% endfor %}
    <a href="{% url 'team:create' %}">[새 팀 등록]</a>
{% endblock %}
